### ISSUE TITLE
OAuth support for Data Connectors

### ISSUE THREAD

**Issue by kristogj** [disruptive-technologies/python-client#109]
Can you add OAuth support for Data Connectors when requesting the Endpoint URL?

**Comment by jhgjeraker** [comment]
Your request has been noted, but please elaborate. Are there any particular implementation or security issues you are having with the [existing signature secret method](https://developer.disruptive-technologies.com/docs/data-connectors/advanced-configurations#signing-events)?

We do have plans to update the verification methods of our Data Connector requests in the future, though whether this will be an expansion of the signature secret scheme or something else has yet to be decided.

**Comment by kristogj** [comment]
Thanks for the quick response. I have an endpoint that can accept data, but it needs a token from Azure AD. This token does not last for very long, so it needs to be updated continuously. Does that make sense?

**Comment by ngerstle-cognite** [comment]
> You can also specify your own headers via the API or Studio application if you need to set custom headers.

What would your recommendation be for handling credentials that must be rotated on a regular basis (ie, hourly)?

Would updating a static authorization header hourly be feasible (using some external timer and the https://developer.disruptive-technologies.com/api#/Data%20Connectors/patch_projects__project__dataconnectors__dataconnector_ endpoint)?



> Your request has been noted, but please elaborate. Are there any particular implementation or security issues you are having with the [existing signature secret method](https://developer.disruptive-technologies.com/docs/data-connectors/advanced-configurations#signing-events)?

I haven't done an analysis or looked for issues, but most APIs/services don't permit custom authentication schemes- many utilize OAuth2, custom token/key based schemes, etc; but do not offer a way to provide payload signing validation logic, or similar. This means that data connectors cannot be directly connected to external services unless they either accept static credentials, permit implementing custom authentication schemes, or don't require authentication.

I am a bit curious- is the signature secret method used here based on a standard?

**Comment by ngerstle-cognite** [comment]
@orjanbruland Is there another place discussion could be continued?

**Comment by orjanbruland** [comment]
@ngerstle-cognite If you send an email to support@disruptive-technologies.com, then we can continue the discussion there.
