### ISSUE TITLE
Feature request: support for creating notifications 

### ISSUE THREAD

**Issue by virgesmith** [disruptive-technologies/python-client#85]
Hi,
This may be the wrong place to request this as I don't think the underlying DT cloud API supports it either, but would it be possible somehow be able to create and view existing notifications (as in DT studio) using the python client?
Thanks,
Andrew

**Comment by vegather** [comment]
Hi Andrew,

There actually is a REST API to create and manage notifications, it's the API that Studio uses. However, this API is currently not documented as we have several changes we want to make to it before making it public. We plan to open up this API and document it once we've had a chance to make the changes we want to it. At that point, we'll also add it to the Python client of course.

Hope that makes sense!

- Vegard

**Comment by virgesmith** [comment]
Thanks! I shall keep an eye out for updates, and use DT studio in the meantime
